import React from "react"
import Quick from '../components/Quick'

export default function Home() {
  return (
    <div>
      <p>
        The iSamples RCN seeks to advance the use of innovative
        cyberinfrastructure to connect physical samples and sample collections
        across the Earth Sciences with digital data infrastructures to
        revolutionize their utility for science. The ultimate goal of this RCN
        is to dramatically improve the discovery, access, sharing, analysis, and
        curation of physical samples and the data generated by their study for
        the benefit of science and society.
      </p>
      <Quick />
    </div>
  )
}
